# Generated by Django 6.0 on 2026-02-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_user_id_b514bd_idx',
            old_name='devicetoken_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_token_bf3234_idx',
            old_name='devicetoken_token_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notification_recipient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notification_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_46ad24_idx',
            old_name='notification_created_idx',
        ),
    ]
