# Generated by Codex on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[
                    ('LIKE', 'Like'),
                    ('COMMENT', 'Comment'),
                    ('POST_LIKE', 'Post Like'),
                    ('POST_COMMENT', 'Post Comment'),
                    ('POST_SAVE', 'Post Save'),
                    ('COMMENT_LIKE', 'Comment Like'),
                    ('COMMENT_REPLY', 'Comment Reply'),
                    ('FOLLOW', 'Follow'),
                    ('ROUTE_LIKE', 'Route Like'),
                    ('ROUTE_COMMENT', 'Route Comment'),
                    ('ROUTE_SAVE', 'Route Save'),
                    ('TRIP_INVITE', 'Trip Invite'),
                    ('WELCOME', 'Welcome'),
                    ('EMAIL_VERIFICATION', 'Email Verification'),
                    ('SYSTEM_ALERT', 'System Alert'),
                ],
                help_text='Event verb that describes why the notification was created',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(
                choices=[
                    ('ACTIVITY', 'Activity'),
                    ('ROUTES', 'Routes'),
                    ('SYSTEM', 'System'),
                ],
                default='ACTIVITY',
                help_text='UI category bucket for filtering and presentation',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_object_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', 'created_at'], name='notificatio_recipie_8f1479_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'verb', 'target_object_ref'], name='notificatio_recipie_c1dfe5_idx'),
        ),
    ]
