"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    env_path = Path(__file__).resolve().parent.parent / '.env'
    if env_path.exists():
        # Ensure backend/.env is the single source of truth in local dev.
        load_dotenv(env_path, override=True)
except ImportError:
    # If python-dotenv is not installed, os.getenv() will still work
    # but will only read from actual environment variables
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    root_env_path = BASE_DIR.parent / '.env'
    if root_env_path.exists():
        load_dotenv(root_env_path, override=False)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--ueb3@y%n+!erqzt*hsj@b*tyzq_)8k%+5k+%6and$(tz60s!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # GIS support
    'django.contrib.gis',
    # Infrastructure
    'infra.apps.InfraConfig',
    # Local apps
    'core',
    'user.apps.UserConfig',
    'locations',
    'recommendations',
    'community',
    'notifications',
    'trips',
    'task_queue',
    'media_storage',
    'ai_service',
    'corsheaders',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Global exception handler (must be near the top to catch all exceptions)
    'core.middleware.GlobalExceptionHandler',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.contrib.gis.db.backends.postgis'),
        'NAME': os.getenv('DB_NAME', 'excursa'),
        'USER': os.getenv('DB_USER', 'excursa_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'excursa_pass'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# MongoDB Configuration for Community App
MONGODB_DATABASES = {
    'default': {
        'name': os.getenv('MONGO_DB_NAME', 'excursa_community'),
        'host': os.getenv('MONGO_HOST', 'localhost'),
        'port': int(os.getenv('MONGO_PORT', '27017')),
        'username': os.getenv('MONGO_USER', ''),
        'password': os.getenv('MONGO_PASSWORD', ''),
        'tz_aware': True,
    }
}

# Configure mongoengine
import mongoengine
try:
    if MONGODB_DATABASES['default']['username'] and MONGODB_DATABASES['default']['password']:
        mongoengine.connect(
            db=MONGODB_DATABASES['default']['name'],
            host=MONGODB_DATABASES['default']['host'],
            port=MONGODB_DATABASES['default']['port'],
            username=MONGODB_DATABASES['default']['username'],
            password=MONGODB_DATABASES['default']['password'],
            tz_aware=MONGODB_DATABASES['default']['tz_aware'],
        )
    else:
        mongoengine.connect(
            db=MONGODB_DATABASES['default']['name'],
            host=MONGODB_DATABASES['default']['host'],
            port=MONGODB_DATABASES['default']['port'],
            tz_aware=MONGODB_DATABASES['default']['tz_aware'],
        )
except Exception as e:
    print(f"MongoDB connection warning: {e}")



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "infra.authentication.RedisAwareJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": os.getenv("JWT_ROTATE_REFRESH_TOKENS", "False").lower() == "true",
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# External API Keys (loaded from environment variables)
# DO NOT commit API keys to version control
GOOGLE_PLACES_API_KEY = os.getenv('GOOGLE_PLACES_API_KEY', None)
FOURSQUARE_API_KEY = os.getenv('FOURSQUARE_API_KEY', None)

# GDAL Configuration
if os.name == 'posix':
    # Auto-detect GDAL library path for Docker (Debian/Ubuntu based images)
    for path in ['/usr/lib/x86_64-linux-gnu/libgdal.so', 
                 '/usr/lib/aarch64-linux-gnu/libgdal.so', 
                 '/usr/lib/libgdal.so']:
        if os.path.exists(path):
            GDAL_LIBRARY_PATH = path
            break


# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

# Celery Beat Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'sync-external-data-every-6-hours': {
        'task': 'task_queue.tasks.sync_external_data_task',
        'schedule': crontab(minute=0, hour='*/6'),  # Every 6 hours
        'args': (51.5074, -0.1278),  # Example: London coordinates
    },
    'calculate-trends-daily': {
        'task': 'task_queue.tasks.calculate_trends_task',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
    },
}


# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@excursa.com')


# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
REDIS_KEY_PREFIX = os.getenv('REDIS_KEY_PREFIX', 'excursa')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# AWS S3 Configuration (for image compression)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'excursa-uploads')

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",  # Expo
    "http://localhost:19006", # Expo Web
    "http://192.168.1.3:8081", # Local LAN Expo Web
]
