# Generated by Django 6.0 on 2026-02-28 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blacklistedpoi',
            new_name='recommendat_expires_4cd6ec_idx',
            old_name='recommendations_blacklisted_poi_expires_at_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='recommendat_user_id_7b8d15_idx',
            old_name='recommendations_interaction_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='recommendat_poi_id_a4382d_idx',
            old_name='recommendations_interaction_poi_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='recommendat_poi_id_7b0757_idx',
            old_name='recommendations_review_poi_id_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='recommendat_created_68238e_idx',
            old_name='recommendations_review_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='trendinglist',
            new_name='recommendat_geohash_89ca31_idx',
            old_name='recommendations_trending_list_geohash_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(help_text='Rating from 0.0 to 5.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='trendinglist',
            name='pois',
            field=models.JSONField(default=list, help_text='List of trending POI IDs (UUID strings)'),
        ),
    ]
