# Generated by Django 6.0 on 2026-02-22 13:55

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The official name of the place', max_length=255)),
                ('address', models.CharField(help_text='Human readable physical address', max_length=512)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='PostGIS: Stores geometry data (SRID=4326) representing Longitude/Latitude', srid=4326)),
                ('category', models.CharField(choices=[('HISTORICAL', 'Historical'), ('NATURE', 'Nature'), ('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment')], help_text='Classification: HISTORICAL, NATURE, FOOD, ENTERTAINMENT etc.', max_length=20)),
                ('average_rating', models.FloatField(default=0.0, help_text='Cached aggregate rating (0.0 - 5.0) to avoid joining review tables on every read')),
                ('external_id', models.CharField(blank=True, help_text='Unique ID from source provider to prevent duplicates', max_length=255, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible storage for structured data')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of keywords used for vector similarity matching in the Recommendation Engine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations_poi',
                'indexes': [models.Index(fields=['external_id'], name='locations_p_externa_a4967a_idx'), models.Index(fields=['category'], name='locations_p_categor_632377_idx')],
            },
        ),
    ]
