# Generated by Django 6.0 on 2026-03-22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPOI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="locations.poi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_pois",
                        to="user.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "locations_saved_poi",
                "unique_together": {("user", "poi")},
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="locations_s_user_id_xyz123_idx",
                    )
                ],
            },
        ),
    ]
