# Generated by Django 6.0 on 2026-03-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_savedpoi'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedpoi',
            new_name='locations_s_user_id_0871e5_idx',
            old_name='locations_s_user_id_xyz123_idx',
        ),
    ]
