# Generated by Django 6.0 on 2026-02-28 15:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='User defined name for the trip', max_length=255)),
                ('start_date', models.DateTimeField(help_text='The scheduled beginning of the trip')),
                ('end_date', models.DateTimeField(help_text='The scheduled end of the trip')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='DRAFT, ACTIVE, COMPLETED, ARCHIVED', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', help_text='PRIVATE (default), PUBLIC (shared on feed)', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cached total cost based on POI metadata', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Reference to the owner of the itinerary', on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(help_text='The sequence number (0, 1, 2...) in the route', validators=[django.core.validators.MinValueValidator(0)])),
                ('arrival_time', models.TimeField(blank=True, help_text='Scheduled arrival time at this stop', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text="User's personal notes", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(help_text='Reference to the parent trip', on_delete=django.db.models.deletion.CASCADE, to='trips.itinerary')),
                ('poi', models.ForeignKey(help_text='Reference to the location being visited', on_delete=django.db.models.deletion.CASCADE, to='locations.poi')),
            ],
            options={
                'ordering': ['itinerary', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='stops',
            field=models.ManyToManyField(help_text='The collection of places to visit. Uses a Through model (ItineraryItem) to store order/sequence.', related_name='itineraries', through='trips.ItineraryItem', to='locations.poi'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['itinerary', 'order_index'], name='trips_itine_itinera_9324d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryitem',
            unique_together={('itinerary', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['user', '-created_at'], name='trips_itine_user_id_0e5251_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['status'], name='trips_itine_status_497f38_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['visibility'], name='trips_itine_visibil_2d5395_idx'),
        ),
    ]
