# Generated by Django 6.0.2 on 2026-03-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Unique identifier for the conversation context",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional title/topic of the conversation",
                        max_length=255,
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores GPS coordinates and other context for recommendations",
                    ),
                ),
                (
                    "conversation_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stores full conversation history for offline access",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this chat session",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "-updated_at"], name="ai_service_c_user_id_cc8119_idx"),
                    models.Index(fields=["session_id"], name="ai_service_c_session_f7ef30_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")],
                        help_text="Who sent the message (user or bot)",
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("card", "Card"),
                            ("richtext", "Rich Text"),
                            ("suggestion", "Suggestion"),
                        ],
                        default="text",
                        help_text="Type of message content",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(help_text="Text content of the message")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (cards, suggestions, etc.)",
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Detected intent from NLP engine",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score of intent detection (0.0-1.0)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Chat session this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_service.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["session", "created_at"], name="ai_service_c_session_2fe3ba_idx"),
                    models.Index(fields=["sender"], name="ai_service_c_sender_ee4f3f_idx"),
                ],
            },
        ),
    ]
