# Generated by Django 6.0 on 2026-03-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_service__session_564936_idx',
            old_name='ai_service_c_session_2fe3ba_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_service__sender_3a3116_idx',
            old_name='ai_service_c_sender_ee4f3f_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='ai_service__user_id_610884_idx',
            old_name='ai_service_c_user_id_cc8119_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='ai_service__session_51d8aa_idx',
            old_name='ai_service_c_session_f7ef30_idx',
        ),
    ]
